name: Перевірка та Тестування

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонування репозиторію
        uses: actions/checkout@v4

      - name: Налаштування Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Встановлення залежностей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Перевірка коду лінтером flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Тестування за допомогою pytest
        run: |
          pytest
        env:
          TELEGRAM_BOT_TOKEN: "test-dummy-token-123"
          ADMIN_TELEGRAM_ID: "123456789"
          GEMINI_API_KEY: "dummy-api-key"
          DB_USER: "dummy"
          DB_PASSWORD: "dummy"
          DB_NAME: "dummy"
